using System.Runtime.Versioning;

namespace PlusUi.desktop.Accessibility;

/// <summary>
/// AT-SPI roles matching ATSPI_ROLE_* constants.
/// </summary>
[SupportedOSPlatform("linux")]
internal enum AtSpiRole
{
    Unknown = 0,
    Alert = 2,
    Animation = 3,
    Arrow = 4,
    Calendar = 5,
    Canvas = 6,
    CheckBox = 7,
    CheckMenuItem = 8,
    ColorChooser = 9,
    ColumnHeader = 10,
    ComboBox = 11,
    DateEditor = 12,
    DesktopIcon = 13,
    DesktopFrame = 14,
    Dialog = 16,
    DirectoryPane = 17,
    DrawingArea = 18,
    Entry = 22,
    FileChooser = 23,
    Filler = 24,
    FocusTraversable = 25,
    Frame = 27,
    GlassPane = 28,
    Heading = 55,
    Image = 31,
    InternalFrame = 32,
    Label = 33,
    LayeredPane = 34,
    Link = 59,
    List = 35,
    ListItem = 36,
    Menu = 37,
    MenuBar = 38,
    MenuItem = 39,
    OptionPane = 40,
    PageTab = 41,
    PageTabList = 42,
    Panel = 43,
    PasswordText = 44,
    PopupMenu = 45,
    ProgressBar = 46,
    PushButton = 47,
    RadioButton = 48,
    RadioMenuItem = 49,
    RootPane = 50,
    RowHeader = 51,
    ScrollBar = 52,
    ScrollPane = 53,
    Separator = 54,
    Slider = 56,
    SpinButton = 57,
    SplitPane = 58,
    StatusBar = 60,
    Table = 61,
    TableCell = 62,
    TableColumnHeader = 63,
    TableRowHeader = 64,
    Text = 66,
    ToggleButton = 67,
    ToolBar = 68,
    ToolTip = 69,
    Tree = 70,
    TreeTable = 71,
    Window = 73
}
