#nullable enable
using System.Text;

namespace PlusUi.SourceGenerators.UiPropGen;

internal static class UiPropCodeBuilder
{
    internal static string GeneratePropertyFile(string namespaceName, string className, string template)
    {
        var sb = new StringBuilder();

        sb.Append("""
            // <auto-generated />
            #nullable enable

            using System.Linq.Expressions;


            """);

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.Append($"namespace {namespaceName};\n\n");
        }

        sb.Append($"public partial class {className}\n{{\n");

        var code = template.Replace("{ClassName}", className);
        sb.Append(code);

        sb.Append("}\n");

        return sb.ToString();
    }
}
